spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id : product-service-route
              uri : http://localhost:6000
              predicates:
                - Path=/product/** , /category/**
              filters:
                  name : RequestRateLimiter
                  args:
                          KeyResolver : "#{@ipKeyResolver}"
                          redis-rate-limiter.replenishRate : 2
                          redis-rate-limiter.burstCapacity : 2



            - id: order-service-route
              uri: http://localhost:6001
              predicates:
                - Path=/order/**

            - id: payment-service-route
              uri: http://localhost:6002
              predicates:
                - Path=/payment/**