spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id : product-service-route
              uri : http://localhost:6000
              predicates:
                - Path=/product/** , /category/**

            - id: order-service-route
              uri: http://localhost:6001
              predicates:
                - Path=/order/**

            - id: payment-service-route
              uri: http://localhost:6002
              predicates:
                - Path=/payment/**